### ISSUE TITLE
Update test to use Spacejam?

### ISSUE THREAD

**Issue by zimme** [arunoda/travis-ci-meteor-packages#40]
It's pretty self-explanatory. What are your thoughts on this?

**Comment by arunoda** [comment]
This does what id does.
We used this for many years and this is stable.
So, we don't have any reason to switch.

That being said, spacejam is a good solution. You can use it very easily with travis.

**Comment by zimme** [comment]
No problem, just a though and I got a valid answer.

Keep up the good work :+1:
